[tool:pytest]
addopts = "-ra --strict-markers --strict-config"
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[coverage:run]
source = src/hash_identifier_cli

[coverage:report]
show_missing = True
skip_covered = False