import typer
from pathlib import Path
from rich import console, box
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from .detector import detect_languages, detect_frameworks
from .generator import generate_gitignore_rules

app = typer.Typer(add_completion=False, no_args_is_help=True)
console = Console()

@app.command(name="generate")
def cli(
    path: Path = typer.Argument(Path("."), help="Project root to scan"),
    preview: bool = typer.Option(False, "--preview/-p", help="Preview rules without writing"),
    write: bool = typer.Option(False, "--write/-w", help="Write to .gitignore"),
    backup: bool = typer.Option(True, "--backup/-b", help="Backup existing .gitignore"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Simulate write without changes"),
    force: bool = typer.Option(False, "--force/-f", help="Overwrite without backup"),
) -> None:
    """Generate tailored .gitignore for project."""
    project_root = path.resolve()
    if not project_root.is_dir():
        typer.echo("❌ Invalid path: not a directory", err=True)
        raise typer.Exit(1)

    typer.echo(f"🔍 Scanning [bold]{project_root}[/bold]...")

    languages = detect_languages(project_root)
    frameworks = detect_frameworks(project_root)

    typer.echo(f"📋 Detected languages: {', '.join(f'{k}({v})' for k,v in languages.items())}")
    typer.echo(f"🔧 Detected frameworks: {', '.join(frameworks) or 'none'}")

    rules_list = generate_gitignore_rules(languages, frameworks)

    gitignore_path = project_root / ".gitignore"
    existing_content = gitignore_path.read_text(encoding="utf-8") if gitignore_path.exists() else ""

    if preview or dry_run:
        table = Table(title="🛡️ Generated .gitignore Rules", box=box.ROUNDED, show_header=True, header_style="bold magenta")
        table.add_column("Category", style="cyan", no_wrap=True)
        table.add_column("Rule", style="green")
        for category, rule in rules_list:
            table.add_row(category.capitalize(), f"`{rule}`")
        console.print(table)

        if existing_content:
            console.print(Panel("📄 Existing .gitignore detected. Use --write to update.", title="Info"))

    if write and not dry_run:
        content = "# Auto-generated by gitignore-generator v" + __import__("gitignore_generator"). __version__ + "\n# https://github.com/cycoders/code/tree/main/gitignore-generator\n\n" + "\n".join(rule for _, rule in rules_list)

        if gitignore_path.exists():
            if force:
                if backup:
                    backup_path = gitignore_path.with_suffix(".gitignore.bak")
                    gitignore_path.rename(backup_path)
                    typer.echo(f"💾 Backed up to [green]{backup_path}[/green]")
            else:
                # Smart update: add only new rules
                existing_rules = set(line.strip() for line in existing_content.splitlines() if line.strip() and not line.startswith("#"))
                new_rules = [rule for _, rule in rules_list if rule.strip() not in existing_rules]
                if new_rules:
                    content = existing_content.rstrip() + "\n\n# Added by gitignore-generator\n" + "\n".join(new_rules)
                    typer.echo(f"➕ Appending [bold]{len(new_rules)}[/bold] new rules")
                else:
                    typer.echo("✅ No new rules needed")
                    raise typer.Exit(0)
        
        gitignore_path.write_text(content, encoding="utf-8")
        typer.echo(f"✅ Wrote [bold]{len(rules_list)}[/bold] rules to [green]{gitignore_path}[/green]")

    if not preview and not write:
        typer.echo("ℹ️ Use --preview or --write")

if __name__ == "__main__":
    app()