from typing import Dict

from rich.console import Console

from rich.markdown import Markdown

from rich.table import Table

from .models import Service


console = Console()


def services_table(services: Dict[str, Service]) -> Table:
    """Rich table of services."""
    table = Table(title="[bold cyan]Docker Compose Services[/]", expand=True)
    table.add_column("Name", style="cyan", no_wrap=True)
    table.add_column("Image", style="magenta")
    table.add_column("Ports", style="green")
    table.add_column("Depends On", style="yellow")
    table.add_column("Networks", style="blue")

    for svc in services.values():
        table.add_row(
            svc.name,
            svc.image or "[dim]-[/]",
            ", ".join(svc.ports[:3]) + ("..." if len(svc.ports) > 3 else ""),
            ", ".join(svc.depends_on[:2]),
            ", ".join(svc.networks[:2]),
        )

    return table


def generate_mermaid(graph: Dict[str, list[str]], services: Dict[str, Service]) -> str:
    """Generate Mermaid flowchart."""

    lines = [
        "flowchart TD",
        "    %% Auto-generated by compose-visualizer",
    ]

    # Nodes
    for node, deps in graph.items():
        label = node
        img = services[node].image
        if img:
            label += f"\n{img.split(':')[0].split('/')[-1]}"
        lines.append(f'    {node}["{label}"]')

    # Edges
    for node, deps in graph.items():
        for dep in deps:
            lines.append(f"    {node} --> {dep}")

    # Styling
    lines.extend([
        "    classDef service fill:#e1f5fe,stroke:#01579b",
        "    class {','.join(graph)} service",
    ])

    return "\n".join(lines)


def render_visualize(graph: Dict[str, list[str]], services: Dict[str, Service], mermaid_code: str):
    """Render full viz output."""
    console.print(services_table(services))
    md = Markdown(f"```mermaid\n{mermaid_code}\n```")
    console.print(md)