[pytest]
DJANGO_SETTINGS_MODULE =
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra -q --strict-markers --strict-config
filterwarnings =
    ignore::pytest.PytestCollectionWarning
    ignore::pytest.PytestConfigWarning