from typing import Dict, List

from jinja2 import Template

from .types import CommitNode


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Git History Viz</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@11.9.0/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({{ config|tojson }});</script>
    <style>
        body { margin: 2rem; font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
        h1 { color: #333; }
        .mermaid { max-width: 100%; height: 80vh; }
    </style>
</head>
<body>
    <h1>Git History ({{ commit_count }} commits)</h1>
    <div class="mermaid">{{ diagram }}</div>
</body>
</html>
"""

Mermaid_CONFIG = {
    "startOnLoad": True,
    "securityLevel": "loose",
    "theme": None,  # overridden
    "flowchart": {"curve": "linear", "useMaxWidth": True},
}


def escape_mermaid(s: str) -> str:
    """Escape Mermaid label content."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_mermaid(
    commits: Dict[str, CommitNode], order: List[str], theme: str
) -> str:
    """Generate Mermaid flowchart source."""
    lines = ["flowchart TD", "    %% Generated by git-history-viz"]

    # Nodes (oldest first for layout)
    for sha in order:
        node = commits[sha]
        label = escape_mermaid(node.message)
        lines.append(f'    {node.short_sha}["{node.short_sha}\n{label}"]')

    # Edges (child --> parent)
    for sha in commits.values():
        node = sha  # type ignore
        for parent_sha in node.parents:
            if parent_sha in commits:
                p_short = commits[parent_sha].short_sha
                lines.append(f"    {node.short_sha} --> {p_short}")

    # Theme styling
    lines.append(f"    classDef _ghv_{theme} fill:#e8f4f8,stroke:#1976d2,stroke-width:2px")
    short_shas = ",".join(n.short_sha for n in commits.values())
    lines.append(f"    class {short_shas} _ghv_{theme}")

    return "\n".join(lines)


def render_html(diagram: str, theme: str) -> str:
    """Render standalone HTML."""
    config = Mermaid_CONFIG.copy()
    config["theme"] = theme
    tpl = Template(HTML_TEMPLATE)
    return tpl.render(
        diagram=diagram, config=config, commit_count=len(diagram.splitlines())
    )
